### ISSUE TITLE
Migrate away from MD5

### ISSUE THREAD

**Issue by sa7mon** [spieglt/FlyingCarpet#1]
MD5 shouldn't be used for anything these days. SHA-256 should be used.

**Comment by spieglt** [comment]
MD5 is only used for comparing the file on either end of the transfer and determining the SSID, not for anything involving secure file transport. I used it rather than SHA-256 because I wanted it to be fast for large files, and I believe SHA-256 is considerably slower. You're right that I should move away from MD5, but I'm not sure what to use that will be as fast yet. Any suggestions? Thanks for the feedback.

**Comment by hdhauk** [comment]
Did a quick benchmark to compare the performance on my macbook:
```
$ go test -bench=.  -benchtime=10s
BenchmarkGetHashSHA256-8               1        1085111796 ns/op
BenchmarkGetHashMD5-8                  5         245030519 ns/op
PASS
ok      github.com/spieglt/flyingcarpet 3.337s
```

I did not try it on a very large file though, only 130MB.

**Comment by spieglt** [comment]
Thanks @hdhauk ! So am I reading that right that the SHA-256 was about 4 times slower?

**Comment by hdhauk** [comment]
Yep. 

From what I gather you aren't really using the hash for anything other than printing to console, so I can't really see the point of switching to SHA256. As long as you aren't using it for anything other than checking for file corruption during transfer (like checking it for malicious tampering, or storing hashed keys), I'd suggest that you stick to MD5. But thats just my 2 cents ;)

**Comment by spieglt** [comment]
Thanks! That was my thought too so I'm going to close this issue. The MD5 already takes a few seconds for multi-gig files so I don't want to make it 4x slower right now.
