### ISSUE TITLE
MacOS ARM download v5.0 doesn't contain ARM version

### ISSUE THREAD

**Issue by suschizu** [spieglt/FlyingCarpet#24]
hello - the version 5.0 MacOS ARM download doesn't contain an ARM version - contains x86_64 instead (https://github.com/spieglt/FlyingCarpet/releases/download/v5.0/FlyingCarpetMac_AppleSilicon_ARM64.zip)

here is the terminal "file" output:

```
file […]/FlyingCarpetMac_AppleSilicon_ARM64_folder/Flying Carpet.app/Contents/MacOS/Flying Carpet: Mach-O 64-bit executable x86_64
```

**Comment by spieglt** [comment]
Ah, thanks for bringing that to my attention @suschizu. I didn't think about the fact that `qtdeploy` would probably just build an x64 version.... I'll have to do some research into whether it's possible to compile for ARM with the current setup. I briefly experimented with switching the GUI to use [Fyne](https://github.com/fyne-io/fyne) because the Qt binding Flying Carpet uses is no longer maintained, but I stopped due to the lack of drag-and-drop, non-native file/folder dialogs, and some other bugs. In any case, does the x86_64 version work for you via Rosetta?

**Comment by spieglt** [comment]
For now, I deleted the non-ARM64 version, renamed the x64 one, and added a note about Rosetta.

**Comment by spieglt** [comment]
It looks like Apple Silicon is only officially supported on Qt 6, and unofficially supported on 5.15.4: https://www.qt.io/blog/qt-on-apple-silicon. Is there a reason you'd need it to be ARM64-native, or does it run on your machine with Rosetta @suschizu?

**Comment by suschizu** [comment]
Hey @spieglt  - sorry for not reacting sooner - I had no internet the last few days :/
So no - I don't need an ARM version - I just noticed it because I've received an error message from my daily mainenance I'm running for our app MacUpdater. The intel version doesn't show any problems - so no stress I just have to fix the configuration in our database  👍
