### ISSUE TITLE
A bug was found on the windows side

### ISSUE THREAD

**Issue by RichardQt** [spieglt/FlyingCarpet#47]
1、When you click to cancel the transfer, the software will freeze
2、In addition, apps under ipados will be incompatible, such as the camera is upside down
All in all a great product

**Comment by spieglt** [comment]
1. It sometimes freezes for a bit during cancelling because it's waiting on the operating system to finish searching for a hotspot, close a connection, etc. If you wait, it should eventually cancel properly. I do think there is an issue when the Cancel button is clicked multiple times while it's frozen and the clicks stack, however. Not sure of the fix for this yet.

2. Do you mean that the instructions are upside down when scanning the QR code? Could you possibly send a screenshot? I don't have an iPad so can't test the hardware-specific features like camera and WiFi.

Thank you!

**Comment by spieglt** [comment]
Hi, version 7.0.4 is available on the App Store and fixes the issue when using the QR code scanner in landscape mode. Please try it on iPadOS and let me know if it’s fixed.

**Comment by RichardQt** [comment]
I am very happy to receive your reply, but I am sorry that the QR scanner upside-down problem has not been fixed on the IpadOS side, as shown in the figure
![IMG_3403(20230716-211623)](https://github.com/spieglt/FlyingCarpet/assets/70936615/f09574f1-e34e-4048-905a-3653cb02962a)

**Comment by spieglt** [comment]
Did you definitely update the app through the App Store? In the new version, the icon and text should be closer together like this.
![IMG_7642](https://github.com/spieglt/FlyingCarpet/assets/22626146/e67d6ce5-3048-4018-a394-f0e3067ef2af)

**Comment by spieglt** [comment]
Closing, fairly certain this was fixed.
