### ISSUE TITLE
Transfers fail from Linux to Android

### ISSUE THREAD

**Issue by excarnateSojourner** [spieglt/FlyingCarpet#52]
Sender: Dell Latitude running Debian 12 with FC installed via .deb.
Receiver: Samsung Galaxy A03 running Android 13 with FC installed via Google Play.
On the sender I open FC, select "Send", "Android", and the file I want to transfer. On the receiver I open FC, select "Receive", "Linux", and the destination folder. The receiver turns on its camera, and I click "Start Transfer" on the sender. Immediately the sender says:
```
Start the transfer on the other device and scan the QR code when prompted.
Starting hotspot flyingCarpet_934b
Error connecting to peer: Could not start hotspot: Error: Connection activation failed: No suitable device found for this connection (device eno1 not available because profile is not compatible with device (mismatching interface name)).
```
The sender displays a QR code only for a split second, but this is still long enough for the receiver to register it. The receiver says `Searching for devices...` and after a few seconds, `No devices found. Make sure the device you want to connect to is turned on and ready to install.`

Both devices are able to connect to my home wifi without issues. I've also tried transferring in the other direction, and that fails in a similar manner.

I'd appreciate any insight you might have on this. Thank you.

**Comment by spieglt** [comment]
Thanks for the great report. The message `Connection activation failed: No suitable device found for this connection (device eno1 not available because profile is not compatible with device (mismatching interface name))` is what I've seen when using a WiFi card on Linux whose driver lacks support for running a hotspot. I have a wireless USB dongle that can host a network on Windows, but when I use the same one with Linux, I had to compile and install the drivers for it, which let me use it as a WiFi client, but not host a hotspot. So I assume that's what's going on here. Are you able to start a hotspot on that Latitude otherwise? The direction of the transfer won't make a difference: when it's Linux and Android, the Linux machine will always host the hotspot.

**Comment by excarnateSojourner** [comment]
Thank you for your fast response. I've now tried creating a hotspot on the Latitude using `nmcli` (following [this guide](https://computingforgeeks.com/create-wi-fi-hotspot-on-linux)) and I get the exact same error, so it seems that is the problem.
I've installed FC on my Windows desktop as well, which is able to transfer to the Android, so that solves the problem for me.
