### ISSUE TITLE
program freezes

### ISSUE THREAD

**Issue by 526614375** [spieglt/FlyingCarpet#72]
Windows send to android，file transfer completed, click  cancel transfer button, program freezes

**Comment by spieglt** [comment]
So the transfer completed successfully, but the UI didn't return to be ready for another transfer? There are certain operations on desktop where it takes several seconds for the OS to respond, such as when it's trying to join or create a hotspot. Unfortunately I do think there are bugs that can happen when the Cancel button is clicked a second time before the first click is done processing. I should add a note to the readme about this. I would like to fix this but the last time I tried I wasn't able to get button inputs not to stack, I believe due to the HTML/Javascript/browser UI.

**Comment by 526614375** [comment]
ok, may I ask how to compile this project on Mac?

**Comment by 526614375** [comment]
> So the transfer completed successfully, but the UI didn't return to be ready for another transfer? There are certain operations on desktop where it takes several seconds for the OS to respond, such as when it's trying to join or create a hotspot. Unfortunately I do think there are bugs that can happen when the Cancel button is clicked a second time before the first click is done processing. I should add a note to the readme about this. I would like to fix this but the last time I tried I wasn't able to get button inputs not to stack, I believe due to the HTML/Javascript/browser UI.

ok, can I ask how to compile this project on Mac? in which path execute what command ?

**Comment by spieglt** [comment]
Yep, there is a section about compilation instructions in the [readme](https://github.com/spieglt/FlyingCarpet/blob/main/README.md): `Mac only: Install XCode. Open FlyingCarpetMac/FlyingCarpetMac/FlyingCarpetMac.xcodeproj and build it.` Be sure to follow the rest of the instructions there too.
